version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: juniorhub-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    networks:
      - juniorhub-network

  # MongoDB Express service (web-based MongoDB admin interface)
  mongo-express:
    image: mongo-express:latest
    container_name: juniorhub-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpassword
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - juniorhub-network

  # Backend service
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: juniorhub-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://root:rootpassword@mongodb:27017/juniorhub?authSource=admin
      - JWT_SECRET=juniorhub_secret_key_change_in_production
      - JWT_EXPIRES_IN=1h
      - JWT_REFRESH_SECRET=juniorhub_refresh_secret_key_change_in_production
      - JWT_REFRESH_EXPIRES_IN=7d
      - CLIENT_URL=http://localhost:4200
    depends_on:
      - mongodb
    networks:
      - juniorhub-network

volumes:
  mongodb_data:
  node_modules:

networks:
  juniorhub-network:
    driver: bridge 